const animeData = [
    {
        id: 1,
        title: "Demon Slayer",
        originalTitle: "Kimetsu no Yaiba",
        image: "https://cdn.myanimelist.net/images/anime/1286/99889.jpg",
        thumbnail: "https://cdn.myanimelist.net/images/anime/1286/99889.jpg",
        description: "Em um Japão feudal infestado por demônios, uma família é atacada, deixando apenas dois sobreviventes: Tanjiro e sua irmã Nezuko, que foi transformada em um demônio. Tanjiro se torna um caçador de demônios para encontrar uma cura para sua irmã e vingar sua família.",
        longDescription: "Em Kimetsu no Yaiba, Tanjiro Kamado é um jovem gentil e inteligente que vive com sua família nas montanhas. Ele se tornou o único sustento da família após a morte de seu pai, fazendo viagens ao vilarejo próximo para vender carvão.\n\nUm dia, ao retornar para casa, ele encontra sua família massacrada por um demônio. Para piorar a situação, sua irmã mais nova, Nezuko, a única sobrevivente, foi transformada em um demônio. Surpreendentemente, porém, ela ainda demonstra sinais de emoções humanas e pensamentos.\n\nDeterminado a curar sua irmã e vingar sua família, Tanjiro embarca em uma jornada para se tornar um 'Caçador de Demônios', uma organização antiga que vem lutando contra os demônios há séculos. Ao longo de sua jornada, Tanjiro encontra aliados e inimigos formidáveis, enquanto o mundo dos demônios e caçadores de demônios se revela cada vez mais complexo e perigoso.",
        studio: "ufotable",
        releaseYear: 2019,
        episodes: 26,
        status: "Em andamento",
        genres: ["Ação", "Fantasia", "Histórico", "Sobrenatural"],
        youtubeLink: "https://www.youtube.com/watch?v=VQGCKyvzIM4",
        mangaLink: "https://mangaplus.shueisha.co.jp/titles/100009"
    },
    {
        id: 2,
        title: "Attack on Titan",
        originalTitle: "Shingeki no Kyojin",
        image: "https://cdn.myanimelist.net/images/anime/10/47347.jpg",
        thumbnail: "https://cdn.myanimelist.net/images/anime/10/47347.jpg",
        description: "A humanidade está à beira da extinção devido ao surgimento dos Titãs, gigantes que devoram humanos. Eren Yeager jura vingança contra os Titãs após sua mãe ser devorada e se junta ao Corpo de Exploração.",
        longDescription: "Há muitos anos, a humanidade foi quase exterminada pelo surgimento repentino dos Titãs, criaturas humanoides gigantes que devoravam humanos aparentemente sem motivo. Os poucos sobreviventes construíram uma cidade fortificada com enormes muralhas para se proteger dos Titãs.\n\nEren Yeager vive com sua família na cidade de Shiganshina, localizada no distrito mais externo da muralha. Sua vida muda drasticamente quando um Titã Colossal aparece e destrói parte da muralha, permitindo que outros Titãs entrem na cidade. Durante o caos, Eren testemunha sua mãe sendo devorada por um Titã.\n\nTraumatizado e enfurecido, Eren jura vingança contra todos os Titãs e se alista no exército junto com seus amigos de infância, Mikasa Ackerman e Armin Arlert. Eles se juntam ao Corpo de Exploração, uma unidade militar de elite que se aventura além das muralhas para estudar os Titãs e encontrar uma maneira de derrotá-los.\n\nAo longo da série, segredos sobre a origem dos Titãs, a história da humanidade e a verdade sobre o mundo são revelados, levando a reviravoltas surpreendentes e dilemas morais complexos.",
        studio: "Wit Studio / MAPPA",
        releaseYear: 2013,
        episodes: 75,
        status: "Completo",
        genres: ["Ação", "Drama", "Fantasia", "Mistério"],
        youtubeLink: "https://www.youtube.com/watch?v=MGRm4IzK1SQ",
        mangaLink: "https://mangaplus.shueisha.co.jp/titles/100879"
    },
    {
        id: 3,
        title: "My Hero Academia",
        originalTitle: "Boku no Hero Academia",
        image: "https://cdn.myanimelist.net/images/anime/10/78745.jpg",
        thumbnail: "https://cdn.myanimelist.net/images/anime/10/78745.jpg",
        description: "Em um mundo onde quase todos possuem superpoderes, Izuku Midoriya nasceu sem nenhuma habilidade. Mesmo assim, ele sonha em se tornar um herói como seu ídolo All Might.",
        longDescription: "Em um mundo onde 80% da população possui algum tipo de superpoder chamado 'Individualidade', Izuku Midoriya é um dos poucos que nasceu sem nenhuma habilidade especial. Mesmo assim, ele nunca desistiu de seu sonho de se tornar um herói profissional como seu ídolo, o lendário All Might, o Símbolo da Paz.\n\nUm dia, após um encontro fatídico com All Might, Izuku descobre que seu ídolo está escondendo um segredo: devido a um ferimento grave, seus poderes estão diminuindo. Impressionado com a determinação e o espírito heroico de Izuku, All Might decide passar sua Individualidade, 'One For All', para o jovem, tornando-o seu sucessor.\n\nAgora com um poder incrível, mas difícil de controlar, Izuku consegue entrar na U.A. High School, a mais prestigiada escola de heróis do Japão. Lá, ele faz amigos e rivais, enfrenta vilões perigosos e aprende o que realmente significa ser um herói.\n\nA jornada de Izuku é cheia de desafios, crescimento pessoal e batalhas épicas, enquanto ele trabalha para dominar seus poderes e eventualmente se tornar o maior herói do mundo.",
        studio: "Bones",
        releaseYear: 2016,
        episodes: 113,
        status: "Em andamento",
        genres: ["Ação", "Comédia", "Super Poderes", "Escola"],
        youtubeLink: "https://www.youtube.com/watch?v=EPVkcwyLQQ8",
        mangaLink: "https://mangaplus.shueisha.co.jp/titles/100017"
    },
    {
        id: 4,
        title: "One Piece",
        originalTitle: "One Piece",
        image: "https://cdn.myanimelist.net/images/anime/6/73245.jpg",
        thumbnail: "https://cdn.myanimelist.net/images/anime/6/73245.jpg",
        description: "Monkey D. Luffy e sua tripulação de piratas exploram a Grand Line em busca do tesouro mais cobiçado do mundo, o 'One Piece', para se tornar o próximo Rei dos Piratas.",
        longDescription: "One Piece se passa em um mundo dominado pelo mar, onde piratas de todo o mundo partem em busca do lendário tesouro conhecido como 'One Piece', deixado pelo falecido Rei dos Piratas, Gol D. Roger. Quem encontrar esse tesouro poderá reivindicar o título de novo Rei dos Piratas.\n\nMonkey D. Luffy, um jovem cujo corpo ganhou propriedades de borracha após comer uma Fruta do Diabo, parte em uma jornada para encontrar o One Piece e se tornar o Rei dos Piratas. Ao longo de sua aventura, ele forma sua própria tripulação, os Piratas do Chapéu de Palha, composta por indivíduos únicos e talentosos.\n\nA tripulação navega pela Grand Line, uma rota marítima perigosa e imprevisível, enfrentando outros piratas, a Marinha (a força militar do Governo Mundial), e diversos outros desafios. Cada membro da tripulação tem seus próprios sonhos e objetivos, que esperam realizar durante a jornada.\n\nA história de One Piece é conhecida por seu vasto mundo, personagens memoráveis, temas de amizade, liberdade e perseguição de sonhos, além de uma narrativa complexa que conecta eventos aparentemente não relacionados em uma trama maior.",
        studio: "Toei Animation",
        releaseYear: 1999,
        episodes: 1000,
        status: "Em andamento",
        genres: ["Ação", "Aventura", "Comédia", "Fantasia", "Shounen"],
        youtubeLink: "https://www.youtube.com/watch?v=S8_YwFLCh4U",
        mangaLink: "https://mangaplus.shueisha.co.jp/titles/100020"
    },
    {
        id: 5,
        title: "Jujutsu Kaisen",
        originalTitle: "Jujutsu Kaisen",
        image: "https://cdn.myanimelist.net/images/anime/1171/109222.jpg",
        thumbnail: "https://cdn.myanimelist.net/images/anime/1171/109222.jpg",
        description: "Yuji Itadori, um estudante do ensino médio com habilidades físicas excepcionais, se junta a uma organização secreta de feiticeiros para eliminar uma poderosa maldição.",
        longDescription: "Jujutsu Kaisen segue a história de Yuji Itadori, um estudante do ensino médio com habilidades atléticas extraordinárias que vive uma vida normal até que seu avô morre e ele encontra um objeto amaldiçoado: um dedo mumificado. Quando seus amigos do Clube de Ocultismo da escola estão em perigo devido a maldições que atacam a escola, Yuji engole o dedo para protegê-los.\n\nO dedo pertence a Ryomen Sukuna, uma poderosa maldição conhecida como o 'Rei das Maldições'. Surpreendentemente, Yuji consegue manter o controle de seu corpo, compartilhando-o com Sukuna. Devido a essa situação única, Satoru Gojo, um poderoso feiticeiro jujutsu, decide levar Yuji para a Escola Técnica de Jujutsu de Tokyo em vez de executá-lo imediatamente.\n\nNa escola, Yuji começa a treinar com outros estudantes de feitiçaria, incluindo Megumi Fushiguro e Nobara Kugisaki, para se tornar um feiticeiro jujutsu. Juntos, eles enfrentam várias maldições perigosas enquanto Yuji busca consumir todos os dedos de Sukuna para eventualmente exorcizá-lo completamente.\n\nA série explora temas de vida, morte, humanidade e o preço do poder, enquanto apresenta um sistema de magia único baseado em emoções negativas e energia amaldiçoada.",
        studio: "MAPPA",
        releaseYear: 2020,
        episodes: 24,
        status: "Em andamento",
        genres: ["Ação", "Sobrenatural", "Demônios", "Escola"],
        youtubeLink: "https://www.youtube.com/watch?v=4A_X-Dvl0ws",
        mangaLink: "https://mangaplus.shueisha.co.jp/titles/100034"
    },
    {
        id: 6,
        title: "Naruto",
        originalTitle: "Naruto",
        image: "https://cdn.myanimelist.net/images/anime/13/17405.jpg",
        thumbnail: "https://cdn.myanimelist.net/images/anime/13/17405.jpg",
        description: "Naruto Uzumaki, um jovem ninja hiperativo, busca reconhecimento de seus pares e sonha em se tornar o Hokage, o líder de sua vila.",
        longDescription: "Naruto é ambientado em um mundo de ninjas, onde países competem por poder militar através de vilas ninja ocultas. A história segue Naruto Uzumaki, um jovem ninja órfão da Vila da Folha (Konoha) que foi rejeitado pelos habitantes da vila devido ao fato de ter a Raposa de Nove Caudas, uma besta demoníaca que atacou a vila, selada dentro dele quando era bebê.\n\nDeterminado a provar seu valor e ganhar o respeito de todos, Naruto sonha em se tornar o Hokage, o ninja mais forte e líder da vila. Apesar de ser inicialmente desajeitado e impulsivo, Naruto trabalha duro para melhorar suas habilidades ninja e formar laços com seus colegas de equipe, Sasuke Uchiha e Sakura Haruno, e seu mentor, Kakashi Hatake.\n\nAo longo da série, Naruto enfrenta diversos inimigos poderosos, descobre segredos sobre seu passado e o mundo ninja, e lida com a deserção de seu melhor amigo e rival, Sasuke. A jornada de Naruto é marcada por temas de perseverança, amizade, traição, redenção e o ciclo de ódio que permeia o mundo ninja.\n\nA série é dividida em duas partes: 'Naruto', que cobre a adolescência inicial do protagonista, e 'Naruto Shippuden', que se passa após um salto temporal de dois anos e meio, mostrando Naruto mais maduro e poderoso.",
        studio: "Studio Pierrot",
        releaseYear: 2002,
        episodes: 220,
        status: "Completo",
        genres: ["Ação", "Aventura", "Comédia", "Super Poder", "Artes Marciais"],
        youtubeLink: "https://www.youtube.com/watch?v=j2hiC9BmJlQ",
        mangaLink: "https://mangaplus.shueisha.co.jp/titles/100023"
    }
];